### ISSUE TITLE
HTTPS kasutuselevõtmine

### ISSUE THREAD

**Issue by tormi** [e-gov/kem-gsavalik#21]
Teen ettepaneku võtta [gsavalik.envir.ee/geoserver](http://gsavalik.envir.ee/geoserver/gwc/service/tms/1.0.0/) serveris kasutusele HTTPS, kuna hetkel ei saa selle vektorväljundit kasutada HTTPS'i kasutavas serveris (näit. https://cdn.rawgit.com/e-gov/thema/devel/kaart/thema/index.html). Veateade:

`Mixed Content: The page at 'https://cdn.rawgit.com/e-gov/thema/devel/kaart/thema/index.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://gsavalik.envir.ee/geoserver/gwc/service/tms/1.0.0/keskkonnainfo:ristipuud@EPSG:3301@geojson/3/4/4.geojson'. This request has been blocked; the content must be served over HTTPS.`

**Comment by tkardi** [comment]
Uurin

**Comment by tkardi** [comment]
HTTPS olemas, automaatne ümbersuunamine HTTP pealt HTTPS peale

**Comment by tormi** [comment]
:+1:
