### ISSUE TITLE
Lageraiealad

### ISSUE THREAD

**Issue by relken** [e-gov/kem-gsavalik#32]
Lisada lageraiealad uude loodava `vesi` schema alla.
Andmekoosseis koosneb ühest atribuuttunnusest:

periood - _string_ tüüpi väli, mis iseloomustab lageraie toimumise ajavahemikku. Võib olla esitatud aastate vahemikuna või üksikaastana, kui on nii teada.

Andmed on saadud erinevate aastate satelliitpiltide võrdlemise teel. Analüüs teostatud Tartu Observatooriumi poolt Keskkonnaagentuuri tellimusel.

Andmete primaarseks kasutuskohaks oleks VeeVeebis olev Estmodeli rakendus, kus teades lageraiealade paiknemist, on võimalik detailsemalt hinnata erinevatelt maakattetüüpidelt pärinevat hajukoormust veekogudele.

**Comment by tkardi** [comment]
:+1: millise atributsiooniga / kasutustingimustega see kiht oleks? Kuna me loome siin teenuseid sisuliselt avalikku kasutusse, siis oleks vaja võimalikele taaskasutajatele hilisemate segaduste ja komplikatsioonide vältimiseks tagada "õiguskindlus". 
See on ilmselt seotud ka tingimustega, millega KAUR need andmed enda valdusesse saanud.
Muude andmehulkade puhul on siin kasutusel CC BY 4.0 (https://creativecommons.org/licenses/by/4.0).

**Comment by relken** [comment]
kasutamisel piiranguid ei ole, võib lisada, et:
Andmed @ CC-BY 4.0 Keskkonnaagentuur.

**Comment by tkardi** [comment]
Andmete osas:

- tekstiveeru `periood` lõin kaheks erinevaks `int` tüüpi veeruks: `periood_a` (kui algus) ja `periood_o` (kui ots). Juhul kui seni perioodi veerus oli üks aastaarv vaid, siis on `periood_a` veeru sisu `NULL`. Nii võiks olla päringute tegemine ("anna mulle ainult selles ajavahes toimunud muudatused"-stiilis) natuke lihtsam
- kihi datastore võtsin shapefaililt ning liitsin ta ülejäänud kihtidega sama loogika alla.
- gwc kahhelduse konfiguratsioonis täpsustasin kihi ümberkastid
- kihinime (name) muutsin `lowercase`'i -> `vesi:lageraiealad`

Kihi kujunduse osas:

![rohe_lageraiealad](https://user-images.githubusercontent.com/8924478/34948056-bc7a1264-fa14-11e7-84be-d723e46d2acf.png)

- rohelise ortofoto taustal ei pruugi roheline kujundus ise hästi hoomatav olla. Ma lisaks piirjoonele kerge heledama "halo" lisaks. Kas see sobib?
- polügonide sisemus võiks olla läbipaistvam: kui piisavalt sisse suurendada nii et alade sisemus muutub arusaadavaks, siis ei kataks sisemus ära selle alla jäävat.

**Comment by relken** [comment]
nõus, et perioodi võiks kaheks erinevaks väljaks tükeldada.
mõte lisada piirjoonele halo ning sisu läbipaistvamaks teha, on ka hea.

**Comment by tkardi** [comment]
lisasin ka mõõtkavapiirangu ~ 1:250K peale: sellest väiksemal mõõtkaval ei ole väga midagi arusaadavat näha.

**Comment by tkardi** [comment]
@relken, see lageraiete kiht on nüüd [olemas](https://gsavalik.envir.ee/geoserver/vesi/ows?service=wms&version=1.1.0&request=getmap&layers=vesi:lageraiealad&styles=&bbox=541770.8788184919,6498139.2237894405,564676.3170942976,6503865.583358392&width=1200&height=300&srs=epsg:3301&format=application/openlayers).

Ma võtaks hea meelega järgmine/ülejärgmine nädal ette ka ülejäänud (seni agserveril olnud) kaardikihtide gsavalikule toomise.

Selle õssu panen praegu kinni, juhul kui on probleeme vesi:lageraiealad kihiga, siis saab uue õssu avada.
