### ISSUE TITLE
Täiendused README.md faili

### ISSUE THREAD

**Issue by tkardi** [e-gov/kem-gsavalik#7]
Kas on midagi, mis peaks olema täpsemalt lahti seletatud/kirjeldatud? 
Kontrolli üle sõnastus :)

**Comment by tormi** [comment]
Kas readmes viidatud [KEM GS URL](http://gsavalik.envir.ee/geoserver/) peaks juba funkama? Hetkel annab 404 veatedet.

**Comment by tormi** [comment]
>Uute kaardikihtide lisamise soovide osas võiks üle käia teemad okestonia/opendata-issue-tracker lehel ning oma soovid ja vajadused sinna kommunikeerida. Seeläbi saame teabe huvipakkuvatest andmetest ühes koos hoida.

Võiks siiski ka siin repos `õssu` (milline tore uussõna ;) ) tekitada, kui seal midagi siia sobivat tekib. Siis saab seal vastava staatuse anda ja siinsele õssule viidata.

**Comment by tkardi** [comment]
> Kas readmes viidatud KEM GS URL peaks juba funkama?

Hea tähelepanek. Kuna gs veebiadmin (../geoserver/web) on seal suletud, puudub praegu korralik "maandumisleht". Mingi lühike sissejuhatav tekst + viited kaardikihtide eelvaadetele äkki. Selle kohta peaks tegema õssu :) 

Muidu hetkel on seal sisu suht kasin ja avatud WMS/WFS päringutele nt ../geoserver/baasandmed/ows? ja ../geoserver/eelis/ows? alt. `baasandmed` on ainult WMS.

> Võiks siiski ka siin repos õssu tekitada, kui seal [okestonia/opendata-issue-tracker] midagi siia sobivat tekib

Jah, lõpuks küll, kuid siia võiks teemana konkreetse kihiga tegelemine üles tulla alles siis kui andmeomanikuga läbi räägitud ja andmed avaldamisele sobival kujul olemas. S.t siin oleks n.ö viimane ponnistus. Ma hoiaks võibolla ka arutelu andmesisu (nt millised atribuutandmed võiks/peaks avaldatama) üle okestonia/opendata-issue-tracker all - oleks arutelu ühes koos. 

Kas tunduks ok nii?

**Comment by tormi** [comment]
Mingi märk võiks tekkida enne, et need, kes oskavad [OIT](https://github.com/okestonia/opendata-issue-tracker/)-d külastamata/teadmata otse siia tulla, oleks ka informeeritud.

**Comment by tormi** [comment]
Ja muidugi toote omanikuna oleks ise huvitet, et minu teenuste disainimine toimuks selleks ellu kutsutud repos ;) OIT kandes hoiaks vaid viidet siia ja teema staatust.

**Comment by tkardi** [comment]
OK, tõsi. Selles mõttes täieti õige. 

Kas selle võiks READMEsse sõnastada siis umbkaudselt nii, et andmevajaduste kogumine käiks opendata-issue-tracker all ja kui on selge et gsavalik suudab sellele andmevajadusele vastata, siis avada siin repos õssu ning viidata konkreetsele õssule OITis. Konkreetse kihi või kihtide atribuutandmete koosseisu üle arutame samuti siin.

Ma teen README täiendamise jaoks selles punktis tõmmise / tõmmiku / tõmbepalve (_pull requesti_, noh :))

**Comment by tormi** [comment]
:+1:

**Comment by tkardi** [comment]
Sulgen selle õssu. Kui README osas vaja edasi töötada, siis teeb seda eraldi õssude kaudu.
